<?php
/**
 * DOMPDF Test Generator
 * This file generates a simple PDF to test DOMPDF functionality
 */

// Reference the Dompdf namespace
use Dompdf\Dompdf;
use Dompdf\Options;

// Try to load DOMPDF
try {
    if (!file_exists(__DIR__ . '/dompdf/autoload.inc.php')) {
        throw new Exception('DOMPDF files not found. Please install DOMPDF first.');
    }
    
    require_once __DIR__ . '/dompdf/autoload.inc.php';
    
    // Check if Dompdf class exists
    if (!class_exists('Dompdf\Dompdf')) {
        throw new Exception('Dompdf class not found. The library might be corrupted or incomplete.');
    }
    
    // Initialize dompdf options
    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $options->set('isPhpEnabled', true);
    $options->set('isRemoteEnabled', true);
    
    // Initialize dompdf
    $dompdf = new Dompdf($options);
    
    // Current date and time for the test
    $currentDateTime = date('F j, Y, g:i a');
    
    // Generate HTML for the test PDF
    $html = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>DOMPDF Test PDF</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 20px;
                color: #333;
            }
            .container {
                max-width: 800px;
                margin: 0 auto;
                border: 1px solid #ccc;
                padding: 20px;
            }
            .header {
                text-align: center;
                padding-bottom: 10px;
                border-bottom: 2px solid #007bff;
                margin-bottom: 20px;
            }
            h1 {
                color: #007bff;
                font-size: 24px;
            }
            .timestamp {
                text-align: right;
                font-style: italic;
                color: #666;
                margin-bottom: 20px;
            }
            .content {
                margin-bottom: 20px;
            }
            .footer {
                text-align: center;
                border-top: 1px solid #eee;
                padding-top: 10px;
                font-size: 12px;
                color: #666;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }
            table, th, td {
                border: 1px solid #ddd;
            }
            th, td {
                padding: 8px;
                text-align: left;
            }
            th {
                background-color: #f2f2f2;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>DOMPDF Test PDF</h1>
            </div>
            
            <div class="timestamp">
                Generated on: ' . $currentDateTime . '
            </div>
            
            <div class="content">
                <h2>Success! DOMPDF is working correctly.</h2>
                <p>This PDF was successfully generated using DOMPDF. If you can see this document, it means that DOMPDF is properly installed and configured on your system.</p>
                
                <h3>Features Tested:</h3>
                <ul>
                    <li>Basic HTML and CSS styling</li>
                    <li>Font rendering</li>
                    <li>Table layout</li>
                    <li>PDF generation and display</li>
                </ul>
                
                <h3>Sample Table:</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Registration Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>John Doe</td>
                            <td>john.doe@example.com</td>
                            <td>' . date('Y-m-d') . '</td>
                        </tr>
                        <tr>
                            <td>Jane Smith</td>
                            <td>jane.smith@example.com</td>
                            <td>' . date('Y-m-d', strtotime('-1 day')) . '</td>
                        </tr>
                        <tr>
                            <td>Robert Johnson</td>
                            <td>robert.johnson@example.com</td>
                            <td>' . date('Y-m-d', strtotime('-2 days')) . '</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            <div class="footer">
                <p>Test PDF generated by DOMPDF v' . DOMPDF_VERSION . ' | PHP ' . phpversion() . '</p>
            </div>
        </div>
    </body>
    </html>
    ';
    
    // Load the HTML content into dompdf
    $dompdf->loadHtml($html);
    
    // Set paper size and orientation (A4, portrait)
    $dompdf->setPaper('A4', 'portrait');
    
    // Render the PDF
    $dompdf->render();
    
    // Output the generated PDF to browser
    header('Content-Type: application/pdf');
    header('Content-Disposition: inline; filename="dompdf_test.pdf"');
    echo $dompdf->output();
    
} catch (Exception $e) {
    // If an error occurs, display it as HTML
    header('Content-Type: text/html; charset=utf-8');
    echo '<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DOMPDF Test Error</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                max-width: 800px;
                margin: 20px auto;
                padding: 20px;
            }
            .error {
                background-color: #f8d7da;
                border: 1px solid #f5c6cb;
                color: #721c24;
                padding: 15px;
                border-radius: 4px;
                margin-bottom: 20px;
            }
            h1 {
                color: #e74c3c;
            }
            code {
                background: #f8f9fa;
                padding: 3px 5px;
                border-radius: 3px;
                font-family: monospace;
            }
            .back {
                display: inline-block;
                background: #3498db;
                color: white;
                padding: 8px 16px;
                border-radius: 4px;
                text-decoration: none;
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
        <h1>Error Generating Test PDF</h1>
        
        <div class="error">
            <strong>Error Message:</strong> ' . htmlspecialchars($e->getMessage()) . '
        </div>
        
        <h2>What to do next:</h2>
        <ol>
            <li>Make sure DOMPDF is correctly installed. Run <code>composer install</code> in the <code>' . htmlspecialchars(__DIR__) . '</code> directory.</li>
            <li>If you installed DOMPDF manually, ensure all files are correctly placed in the <code>' . htmlspecialchars(__DIR__) . '/dompdf</code> directory.</li>
            <li>Check PHP error logs for additional details about this error.</li>
        </ol>
        
        <a href="test.php" class="back">Back to DOMPDF Test Page</a>
    </body>
    </html>';
} 